# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('photo', models.URLField(verbose_name='Photo')),
            ],
            options={
                'verbose_name': ('Speaker',),
                'verbose_name_plural': 'Speakers',
            },
        ),
    ]
