# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='Start')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('speakers', models.ManyToManyField(blank=True, to='core.Speaker')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'verbose_name': ('Contact',),
            },
        ),
    ]
