# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_talk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='Start')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slots', models.IntegerField(verbose_name='Slots')),
                ('speakers', models.ManyToManyField(blank=True, to='core.Speaker')),
            ],
            options={
                'verbose_name_plural': 'Talks',
                'verbose_name': ('Talk',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': ('Talk',), 'verbose_name_plural': 'Talks'},
        ),
    ]
