# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161012_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
        migrations.AlterModelOptions(
            name='courseold',
            options={'verbose_name': ('Course',), 'verbose_name_plural': 'Courses'},
        ),
    ]
